### ISSUE TITLE
Irritat Hacks hacks hacks Hacks hacks hacks 

### ISSUE THREAD

**Issue by valoeghese** [The-HyperZone/Beacon#2]
**Is your feature request related to a problem? Please describe.**
Don't you hate it when JustSnoopy30 becomes an operator randomly, y'know?

**Describe the solution you'd like**
Remove a few lines of code from your player management :wink::

**Describe alternatives you've considered**
Not using the mod

**Additional context**
I saw that code :eyes:

**Comment by hYdos** [comment]
// Not ready for production yet as warned, use at your own risk (of me being op)

**Comment by TheMadHau5** [comment]
:concern:

**Comment by jearmstrong21** [comment]
👀

**Comment by Justsnoopy30** [comment]
Hmm? There's a comment as hYdos said:
`// Not ready for production yet as warned, use at your own risk (of me being op)`

**Comment by Justsnoopy30** [comment]
I'll provide a config option to turn that off soon.
